#!/usr/bin/env bash
# a Bash script that transfers a file from our client to a server

count=$(echo $* | wc -w)
if (($count < 3)); then
        echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	if [ -z $4 ]; then
		scp -o StrictHostKeyChecking=no -i ~/.ssh/school $1 $3@$2:~/
	else
		scp -o StrictHostKeyChecking=no -i $4 $1 $3@$2:~/
	fi
fi
