#!/usr/bin/env bash
a Bash script that configures a new Ubuntu machine to respect above requirements
# (this script will be run on the server itself)

sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
