#!/usr/bin/env bash
# a Bash script that configures a new Ubuntu machine to respect above requirements
# (this script will be run on the server itself)

apt-get update
apt-get install nginx -y
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
