#!/usr/bin/env bash
# a script that install nginx and make some configuration

sudo apt-get update
sudo apt-get install nginx -y
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo echo "Ceci n'est pas une page" > /var/www/html/404.html

printf %s "server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;

        # Add index.php to the list if you are using PHP
        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }

        error_page 404 /404.html;
        location = /404.html {
                root /var/www/html;
        }
}" > /etc/nginx/sites-available/default

# Configure header
content="http {\n\n\tadd_header X-Served-By \"$(hostname)\"";
sudo sed -i "s|http {|${content}|g" /etc/nginx/nginx.conf

sudo service nginx start
