#!/usr/bin/env bash

printf %s "
backend web-backend
        balance roundrobin
        server web-01 54.88.64.221:80 check
        server web-02 54.87.212.173:80 check

frontend web-frontend
        bind *:80
        default_backend web-backend" >> file
