#!/usr/bin/env bash
# a Bash script that configures a server
cat /etc/nginx/sites-available/default > /etc/nginx/sites-enabled/default
sudo sed -i 's/status_of_proc -p $PID/status_of_proc -p -12/g' /etc/init.d/nginx
sudo service nginx restart
