#!/usr/bin/env bash
# This script is displaying "Best School" 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.

i=0
while (( i < 10 )); do
	echo "Best School"
	if [ $i -eq 8 ]; then #8 cus loop starts from 0
		echo "Hi"
	fi
	(( i++ ))
done
