#!/usr/bin/env bash
#  A Bash script that displays:
# The content of the current directory in a list format
# Where only the part of the name after the first dash is displayed

filename=""
ls -I "list" > .list
for file in $(cat .list); do
	filename="${file#*-}"
	echo "$filename"
done
rm .list
