#!/usr/bin/env bash
# A Bash script that displays:
# The content of the current directory in a list format
# Where only the part of the name after the first dash is displayed

filename=""
for file in *; do
	filename="${file#*-}" # Extracts the part of the filename before the first '-'
	echo "$filename"
done
