#!/usr/bin/env bash
# Loop through files in the current directory
for file in *; do
    # Check if the file is not hidden
    if [[ ${file:0:1} != '.' ]]; then
        # Extract the part of the name after the first dash
        name=$(echo "$file" | cut -d '-' -f 2-)
        # Print the modified name
        echo "$name"
    fi
done

