#!/usr/bin/env bash
# A Bash script that configures an Ubuntu server with the below requirements.
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.

cp /etc/hosts ./hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' hosts.new
sed -i 's/157.240.11.35/8.8.8.8/' hosts.new

cat hosts.new > /etc/hosts
