#!/usr/bin/env bash
# a Bash script that configures the container to fit the above requirements

sudo sed -i 's/user www-data/user nginx/g' /etc/nginx/nginx.conf

# nginx listening on all active IPs on port 8080
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default

# enable read mode for nginx user
sudo chmod 644 /etc/nginx/nginx.conf

# Get pid of process running in port 8080 and kill it
pkill apache2

sudo -u nginx service nginx restart
