#!/usr/bin/env bash
# a Bash script that configures the container to fit the above requirements
chmod +r /etc/nginx/nginx.conf
sudo sh -c "sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf"
sudo sh -c "sed -i 's/80/8080/g' /etc/nginx/sites-available/default"
sudo -u nginx service nginx restart
