#!/usr/bin/env bash
# a Bash script that configures the container to a certain requirement
sudo sed -i 's/user www-data/user nginx/g' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart
