#!/usr/bin/env bash
# a Bash script that uses ssh to connect to your server using the private key ~/.ssh/school with the user ubuntu

cat ~/.ssh/school.pub | ssh ubuntu@54.88.64.221 "mkdir -p ~/.ssh && cat >> ~/.ssh/authorized_keys"
ssh-add ~/.ssh/school
ssh ubuntu@54.88.64.221
